# Hexo 博客配置
title: kirito
subtitle: 醒醒 该写代码了
description: 无限进步
author: ljm
language: zh-Hans
timezone: Asia/Shanghai
url: https://kiritoowo.github.io
root: /
permalink: :year/:month/:day/:title/
theme: next
theme_config:
  scheme: Pisces
  sidebar:
    position: left
    display: post
  menu:
    home: /||home
    categories: /categories/||th
    archives: /archives/||archive
  avatar: /images/avatar.jpg
  author: ljm
  description: 无限进步
  social:
    GitHub: https://github.com/kiritoowo || github
  post_meta:
    item_text: true
  mermaid:
    enable: true
  custom_file_path:
    style: source/_data/styles.styl
  footer:
    since: 2018
  footerpowered:
    enable: true
  search:
    path: search.json
    field: post
    format: html
    limit: 10000
  local_search:
    enable: true
    trigger: auto
    top_n_per_article: 1
  codeblock:
    theme:
      light: normal
      dark: night
  motion:
    enable: false
  pace: false
  language: zh-CN
deploy:
  type: git
  repo: https://github.com/kiritoowo/kiritoowo.github.io.git
  branch: master
  message: "Hexo deploy: {{ now('YYYY-MM-DD HH:mm:ss') }}"
source_dir: source
public_dir: public
